# Generated by Django 4.2.1 on 2023-05-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin_app', '0002_users_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_image',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
