# Generated by Django 4.1.7 on 2023-04-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sno', models.IntegerField()),
                ('Name', models.CharField(max_length=50)),
                ('Class', models.IntegerField()),
                ('Age', models.IntegerField()),
                ('Teacher', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sno', models.IntegerField()),
                ('Name', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Subject', models.CharField(max_length=25)),
            ],
        ),
    ]
