# Generated by Django 4.2.1 on 2023-05-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_app', '0002_mysqlmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysqlmodel',
            name='web',
            field=models.URLField(),
        ),
    ]
