# Generated by Django 4.1.7 on 2023-05-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_app', '0004_rename_country_mysqlmodel_county_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='Files')),
            ],
        ),
    ]
