# Generated by Django 4.1.7 on 2023-05-18 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm_app', '0005_my_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mysqlmodel',
            new_name='Product',
        ),
    ]
