# Generated by Django 4.1.7 on 2023-05-18 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm_app', '0006_rename_mysqlmodel_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='zip_code',
            new_name='zip',
        ),
    ]
