# Generated by Django 4.1.7 on 2023-05-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_app', '0007_rename_zip_code_product_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='zip',
            field=models.CharField(max_length=100),
        ),
    ]
