# Generated by Django 4.1.7 on 2023-03-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0003_delete_tempstore_simpleappusers_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleappusers',
            name='image',
            field=models.ImageField(default='', upload_to='media'),
        ),
    ]
