# Generated by Django 4.1.7 on 2023-03-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0006_alter_simpleappusers_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleappusers',
            name='image',
            field=models.FileField(default=None, null=True, upload_to='images/'),
        ),
    ]
