# Generated by Django 4.1.7 on 2023-03-30 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0009_simpleappusers_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simpleappusers_image',
            name='date',
        ),
    ]
